# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import adminmaster_pb2 as adminmaster__pb2


class AdminMasterStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Ping = channel.unary_unary(
                '/adminmaster.AdminMaster/Ping',
                request_serializer=adminmaster__pb2.Empty.SerializeToString,
                response_deserializer=adminmaster__pb2.Pong.FromString,
                )
        self.ListServers = channel.unary_unary(
                '/adminmaster.AdminMaster/ListServers',
                request_serializer=adminmaster__pb2.Empty.SerializeToString,
                response_deserializer=adminmaster__pb2.ServerList.FromString,
                )


class AdminMasterServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Ping(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListServers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AdminMasterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=adminmaster__pb2.Empty.FromString,
                    response_serializer=adminmaster__pb2.Pong.SerializeToString,
            ),
            'ListServers': grpc.unary_unary_rpc_method_handler(
                    servicer.ListServers,
                    request_deserializer=adminmaster__pb2.Empty.FromString,
                    response_serializer=adminmaster__pb2.ServerList.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'adminmaster.AdminMaster', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AdminMaster(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/adminmaster.AdminMaster/Ping',
            adminmaster__pb2.Empty.SerializeToString,
            adminmaster__pb2.Pong.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListServers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/adminmaster.AdminMaster/ListServers',
            adminmaster__pb2.Empty.SerializeToString,
            adminmaster__pb2.ServerList.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
