// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: proto/adminmaster.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AdminMaster_Ping_FullMethodName        = "/adminmaster.AdminMaster/Ping"
	AdminMaster_ListServers_FullMethodName = "/adminmaster.AdminMaster/ListServers"
)

// AdminMasterClient is the client API for AdminMaster service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AdminMasterClient interface {
	Ping(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Pong, error)
	ListServers(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ServerList, error)
}

type adminMasterClient struct {
	cc grpc.ClientConnInterface
}

func NewAdminMasterClient(cc grpc.ClientConnInterface) AdminMasterClient {
	return &adminMasterClient{cc}
}

func (c *adminMasterClient) Ping(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Pong, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Pong)
	err := c.cc.Invoke(ctx, AdminMaster_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminMasterClient) ListServers(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ServerList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ServerList)
	err := c.cc.Invoke(ctx, AdminMaster_ListServers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdminMasterServer is the server API for AdminMaster service.
// All implementations must embed UnimplementedAdminMasterServer
// for forward compatibility.
type AdminMasterServer interface {
	Ping(context.Context, *Empty) (*Pong, error)
	ListServers(context.Context, *Empty) (*ServerList, error)
	mustEmbedUnimplementedAdminMasterServer()
}

// UnimplementedAdminMasterServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAdminMasterServer struct{}

func (UnimplementedAdminMasterServer) Ping(context.Context, *Empty) (*Pong, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedAdminMasterServer) ListServers(context.Context, *Empty) (*ServerList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListServers not implemented")
}
func (UnimplementedAdminMasterServer) mustEmbedUnimplementedAdminMasterServer() {}
func (UnimplementedAdminMasterServer) testEmbeddedByValue()                     {}

// UnsafeAdminMasterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdminMasterServer will
// result in compilation errors.
type UnsafeAdminMasterServer interface {
	mustEmbedUnimplementedAdminMasterServer()
}

func RegisterAdminMasterServer(s grpc.ServiceRegistrar, srv AdminMasterServer) {
	// If the following call pancis, it indicates UnimplementedAdminMasterServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AdminMaster_ServiceDesc, srv)
}

func _AdminMaster_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminMasterServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminMaster_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminMasterServer).Ping(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminMaster_ListServers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminMasterServer).ListServers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminMaster_ListServers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminMasterServer).ListServers(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// AdminMaster_ServiceDesc is the grpc.ServiceDesc for AdminMaster service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AdminMaster_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "adminmaster.AdminMaster",
	HandlerType: (*AdminMasterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _AdminMaster_Ping_Handler,
		},
		{
			MethodName: "ListServers",
			Handler:    _AdminMaster_ListServers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/adminmaster.proto",
}
