// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: proto/adminmaster.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_adminmaster_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_adminmaster_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_adminmaster_proto_rawDescGZIP(), []int{0}
}

type Pong struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pong) Reset() {
	*x = Pong{}
	mi := &file_proto_adminmaster_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pong) ProtoMessage() {}

func (x *Pong) ProtoReflect() protoreflect.Message {
	mi := &file_proto_adminmaster_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pong.ProtoReflect.Descriptor instead.
func (*Pong) Descriptor() ([]byte, []int) {
	return file_proto_adminmaster_proto_rawDescGZIP(), []int{1}
}

func (x *Pong) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ServerList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Names         []string               `protobuf:"bytes,1,rep,name=names,proto3" json:"names,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerList) Reset() {
	*x = ServerList{}
	mi := &file_proto_adminmaster_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerList) ProtoMessage() {}

func (x *ServerList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_adminmaster_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerList.ProtoReflect.Descriptor instead.
func (*ServerList) Descriptor() ([]byte, []int) {
	return file_proto_adminmaster_proto_rawDescGZIP(), []int{2}
}

func (x *ServerList) GetNames() []string {
	if x != nil {
		return x.Names
	}
	return nil
}

var File_proto_adminmaster_proto protoreflect.FileDescriptor

const file_proto_adminmaster_proto_rawDesc = "" +
	"\n" +
	"\x17proto/adminmaster.proto\x12\vadminmaster\"\a\n" +
	"\x05Empty\" \n" +
	"\x04Pong\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\"\n" +
	"\n" +
	"ServerList\x12\x14\n" +
	"\x05names\x18\x01 \x03(\tR\x05names2x\n" +
	"\vAdminMaster\x12-\n" +
	"\x04Ping\x12\x12.adminmaster.Empty\x1a\x11.adminmaster.Pong\x12:\n" +
	"\vListServers\x12\x12.adminmaster.Empty\x1a\x17.adminmaster.ServerListB\x14Z\x12server/proto;protob\x06proto3"

var (
	file_proto_adminmaster_proto_rawDescOnce sync.Once
	file_proto_adminmaster_proto_rawDescData []byte
)

func file_proto_adminmaster_proto_rawDescGZIP() []byte {
	file_proto_adminmaster_proto_rawDescOnce.Do(func() {
		file_proto_adminmaster_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_adminmaster_proto_rawDesc), len(file_proto_adminmaster_proto_rawDesc)))
	})
	return file_proto_adminmaster_proto_rawDescData
}

var file_proto_adminmaster_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_adminmaster_proto_goTypes = []any{
	(*Empty)(nil),      // 0: adminmaster.Empty
	(*Pong)(nil),       // 1: adminmaster.Pong
	(*ServerList)(nil), // 2: adminmaster.ServerList
}
var file_proto_adminmaster_proto_depIdxs = []int32{
	0, // 0: adminmaster.AdminMaster.Ping:input_type -> adminmaster.Empty
	0, // 1: adminmaster.AdminMaster.ListServers:input_type -> adminmaster.Empty
	1, // 2: adminmaster.AdminMaster.Ping:output_type -> adminmaster.Pong
	2, // 3: adminmaster.AdminMaster.ListServers:output_type -> adminmaster.ServerList
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_adminmaster_proto_init() }
func file_proto_adminmaster_proto_init() {
	if File_proto_adminmaster_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_adminmaster_proto_rawDesc), len(file_proto_adminmaster_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_adminmaster_proto_goTypes,
		DependencyIndexes: file_proto_adminmaster_proto_depIdxs,
		MessageInfos:      file_proto_adminmaster_proto_msgTypes,
	}.Build()
	File_proto_adminmaster_proto = out.File
	file_proto_adminmaster_proto_goTypes = nil
	file_proto_adminmaster_proto_depIdxs = nil
}
