# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: adminmaster.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x61\x64minmaster.proto\x12\x0b\x61\x64minmaster\"\x07\n\x05\x45mpty\"\x17\n\x04Pong\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1b\n\nServerList\x12\r\n\x05names\x18\x01 \x03(\t2x\n\x0b\x41\x64minMaster\x12-\n\x04Ping\x12\x12.adminmaster.Empty\x1a\x11.adminmaster.Pong\x12:\n\x0bListServers\x12\x12.adminmaster.Empty\x1a\x17.adminmaster.ServerListB\x14Z\x12server/proto;protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'adminmaster_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\022server/proto;proto'
  _globals['_EMPTY']._serialized_start=34
  _globals['_EMPTY']._serialized_end=41
  _globals['_PONG']._serialized_start=43
  _globals['_PONG']._serialized_end=66
  _globals['_SERVERLIST']._serialized_start=68
  _globals['_SERVERLIST']._serialized_end=95
  _globals['_ADMINMASTER']._serialized_start=97
  _globals['_ADMINMASTER']._serialized_end=217
# @@protoc_insertion_point(module_scope)
